### ISSUE TITLE
Highlighting is difficult, particularly in bulleted sections

### ISSUE THREAD

**Issue by remybrommer** [marketmuse/editor#10]
https://www.loom.com/share/af6b29ba7bb44ffe96e532a2a60f4578
This video shows that the highlighting jumps around when a bulleted section is selected. This occurred in many other places that I tested it. Highlighting in general needs to be tested under many different scenarios.

**Comment by oguzgelal** [comment]
Fixed here https://github.com/marketmuse/editor/commit/5ffce70b96acacee221b737f44bf5da337a0dbe7. It'll be in the next version.
