### ISSUE TITLE
Adding long form articles crashes the editor

### ISSUE THREAD

**Issue by gentle-noah** [marketmuse/editor#8]
If I try to fetch the following article: https://www.gq.com/story/truck-stop-killer-gq-november-2012

Everything goes white and stops working.

<img width="866" alt="Screen Shot 2020-03-26 at 11 55 44 AM" src="https://user-images.githubusercontent.com/4295346/77667547-bdc79400-6f58-11ea-9491-445a8d60c537.png">

**Comment by oguzgelal** [comment]
Fixed: https://github.com/marketmuse/editor/commit/2d81efd7ee0f977fbe6e652cb790770ef694c8c4
